spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.SpringSerializer
      value-seralizer: org.apache.kafka.common.serialization.SpringSerializer

topic:
  enderco-cliente: topic_endereco_cliente

server:
  port: 8081